services:
  classification:
    restart: unless-stopped
    build:
      context: .
      args:
        - HOST_MODEL_PATH=good-model-2.tflite

    environment:
      - MIN_CONFIDENCE_PERCENT=70
      - MIN_REPRESENTANT_CONFIDENCE_PERCENT=65
      - MODEL_LABELS=BC,BE,BhBl,BlBh,None,Unfinished,XB

    ports:
      - "9197:8000"
